### ISSUE TITLE
Read access required

### ISSUE THREAD

**Issue by bibaev** [bibaev/code-completion-evaluation#96]
Чтобы повторить нужно запустить плагин для питона

```
Details: Current thread: Thread[Generating actions for selected files,4,Idea Thread Group] 1799738828
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2019.3#IU-__BUILD__ IDEA, eap:true, os:Windows 10 10.0, java-version:Oracle Corporation 1.8.0_201-b09,6,Idea Thread Group] 1357245778

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:995)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:182)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:594)
	at com.intellij.psi.impl.source.SpineRef.getStub(SpineRef.java:32)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStub(StubBasedPsiElementBase.java:363)
	at com.jetbrains.python.psi.impl.PyTargetExpressionImpl.getName(PyTargetExpressionImpl.java:82)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyTargetExpression(PsiPythonVisitor.kt:58)
	at com.jetbrains.python.psi.impl.PyTargetExpressionImpl.acceptPyVisitor(PyTargetExpressionImpl.java:76)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyStatement(PyElementVisitor.java:165)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyAssignmentStatement(PyElementVisitor.java:101)
	at com.jetbrains.python.psi.impl.PyAssignmentStatementImpl.acceptPyVisitor(PyAssignmentStatementImpl.java:38)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyStatementList(PyElementVisitor.java:193)
	at com.jetbrains.python.psi.impl.PyStatementListImpl.acceptPyVisitor(PyStatementListImpl.java:25)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyConditionalStatementPart(PyElementVisitor.java:265)
	at com.jetbrains.python.psi.impl.PyConditionalStatementPartImpl.acceptPyVisitor(PyConditionalStatementPartImpl.java:26)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyStatement(PyElementVisitor.java:165)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyIfStatement(PyElementVisitor.java:145)
	at com.jetbrains.python.psi.impl.PyIfStatementImpl.acceptPyVisitor(PyIfStatementImpl.java:22)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyStatementList(PyElementVisitor.java:193)
	at com.jetbrains.python.psi.impl.PyStatementListImpl.acceptPyVisitor(PyStatementListImpl.java:25)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.acceptPyVisitor(PyBaseElementImpl.java:80)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyStatement(PyElementVisitor.java:165)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyIfStatement(PyElementVisitor.java:145)
	at com.jetbrains.python.psi.impl.PyIfStatementImpl.acceptPyVisitor(PyIfStatementImpl.java:22)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyStatementList(PyElementVisitor.java:193)
	at com.jetbrains.python.psi.impl.PyStatementListImpl.acceptPyVisitor(PyStatementListImpl.java:25)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.acceptPyVisitor(PyBaseElementImpl.java:80)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyStatement(PyElementVisitor.java:165)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyForStatement(PyElementVisitor.java:149)
	at com.jetbrains.python.psi.impl.PyForStatementImpl.acceptPyVisitor(PyForStatementImpl.java:21)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyStatementList(PyElementVisitor.java:193)
	at com.jetbrains.python.psi.impl.PyStatementListImpl.acceptPyVisitor(PyStatementListImpl.java:25)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyFunction(PyElementVisitor.java:201)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyFunction(PsiPythonVisitor.kt:103)
	at com.jetbrains.python.psi.impl.PyFunctionImpl.acceptPyVisitor(PyFunctionImpl.java:553)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyStatementList(PyElementVisitor.java:193)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyClass(PsiPythonVisitor.kt:112)
	at com.jetbrains.python.psi.impl.PyClassImpl.acceptPyVisitor(PyClassImpl.java:132)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:72)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:733)
	at com.jetbrains.python.psi.PyRecursiveElementVisitor.visitElement(PyRecursiveElementVisitor.java:13)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyElement(PyElementVisitor.java:25)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyElement(PsiPythonVisitor.kt:79)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyFile(PyElementVisitor.java:209)
	at org.jb.cce.psi.PsiPythonVisitor.visitPyFile(PsiPythonVisitor.kt:37)
	at com.jetbrains.python.psi.impl.PyFileImpl.accept(PyFileImpl.java:253)
	at org.jb.cce.psi.PsiConverter.build(PsiConverter.kt:22)
	at org.jb.cce.CompletionEvaluator.generateActions(CompletionEvaluator.kt:84)
	at org.jb.cce.CompletionEvaluator.access$generateActions(CompletionEvaluator.kt:28)
	at org.jb.cce.CompletionEvaluator$evaluateUnderProgress$task$1.run(CompletionEvaluator.kt:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:895)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:538)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:409)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:409)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:272)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bibaev** [comment]
Fixed in #94
